//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTrackWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> AppointmentDTTM { get; set; }
        public Nullable<System.DateTime> CreatedDTTM { get; set; }
        public Nullable<System.DateTime> UpdatedDTTM { get; set; }
    }
}
