//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTrackWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediTrackDBEntities : DbContext
    {
        public MediTrackDBEntities()
            : base("name=MediTrackDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Med_Appt_Mapper> Med_Appt_Mapper { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<Medication_DE> Medication_DE { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<Problem_Appt_Mapper> Problem_Appt_Mapper { get; set; }
        public virtual DbSet<Problem_DE> Problem_DE { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
